services:
  - type: web
    name: stellar-shipers
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn stellar_shipers.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1,stellarshipers.com,www.stellarshipers.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com,https://stellarshipers.com,https://www.stellarshipers.com"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
      - key: DEFAULT_FROM_EMAIL
        value: "STELLAR SHIPERS <stellarshipper45@gmail.com>"
      - key: ADMIN_NOTIFICATION_EMAIL
        value: "stellarshipper45@gmail.com"