# Generated by Django 5.2.14 on 2026-10-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='STELLAR SHIPERS', max_length=200)),
                ('primary_email', models.EmailField(default='contact@stellarshipers.com', help_text='Primary corporate email address', max_length=254)),
                ('primary_phone', models.CharField(default='Available upon inquiry / B2B RFQ', help_text='Corporate telephone or desk contact', max_length=100)),
                ('address', models.CharField(blank=True, default='India', help_text='Registered office jurisdiction', max_length=255)),
                ('gstin', models.CharField(blank=True, help_text='15-character Indian Goods & Services Tax Identification Number (e.g. 07AAAAA0000A1Z5)', max_length=25, null=True)),
                ('iec', models.CharField(blank=True, help_text='10-digit DGFT Importer-Exporter Code issued by Govt of India', max_length=25, null=True)),
                ('show_gstin', models.BooleanField(default=True, help_text='Display GSTIN publicly on website footer and trade documentation areas')),
                ('show_iec', models.BooleanField(default=True, help_text='Display IEC publicly on website footer and trade documentation areas')),
                ('operational_scope', models.CharField(default='B2B Maritime Cargo & Bulk Agro-Industrial Export Coordination (Exclusively wholesale freight; not a consumer parcel courier or retail package tracking entity).', help_text='Public scope statement preventing automated confusion with retail courier/parcel delivery tracking', max_length=350)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile & Registration',
                'verbose_name_plural': 'Company Profile & Registrations',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('other', 'Other Platform')], default='linkedin', max_length=20)),
                ('display_name', models.CharField(help_text='Display label (e.g. "LinkedIn", "Instagram", "WhatsApp Desk")', max_length=100)),
                ('url', models.URLField(help_text='Full target URL (e.g. https://www.linkedin.com/company/stellarshipers)', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this channel is displayed publicly')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Channel',
                'verbose_name_plural': 'Social Media Channels',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
